services:
  web:
    image: nginx:stable
    restart: always
    links:
      - php
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/ngnix.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    volumes:
      - ./src:/var/www

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: rmsoft
    ports:
      - 8080:8080

  composer:
    image: composer:latest
    depends_on:
      - php
    volumes:
      - ./src:/app
    command: install

volumes: 
  mysql:

networks:
  default:
    name: nginx-proxy-manager_default
